// Memory System - Quick Test/Verification
// Run this to verify the memory system is working

import { AdvancedMemoryBank } from './advanced_memory_bank.js';
import { MemoryAwarePrompter } from './memory_aware_prompter.js';
import MEMORY_QUICK_COMMANDS from './memory_quick_commands.js';

export async function testMemorySystem() {
    console.log('\n========== MEMORY SYSTEM TEST ==========\n');
    
    // Create a test agent mock
    const mockAgent = {
        name: 'TestBot',
        currentSituation: 'testing'
    };
    
    try {
        // Test 1: Initialize memory
        console.log('Test 1: Initializing memory...');
        const memory = new AdvancedMemoryBank(mockAgent.name);
        mockAgent.memory_bank = memory;
        mockAgent.memory_prompter = new MemoryAwarePrompter(mockAgent);
        console.log('✓ Memory initialized successfully\n');
        
        // Test 2: Short-term memory
        console.log('Test 2: Short-term memory...');
        MEMORY_QUICK_COMMANDS.addEvent(memory, 'Started testing');
        MEMORY_QUICK_COMMANDS.addEvent(memory, 'Found some diamonds');
        MEMORY_QUICK_COMMANDS.addEvent(memory, 'Built a small shelter');
        const recentEvents = MEMORY_QUICK_COMMANDS.getRecentEvents(memory);
        console.log('Recent events:', recentEvents);
        console.log('✓ Short-term memory working\n');
        
        // Test 3: Long-term memory
        console.log('Test 3: Long-term memory...');
        MEMORY_QUICK_COMMANDS.setHome(memory, 100, 65, 0);
        MEMORY_QUICK_COMMANDS.rememberPlace(memory, 'diamond_cave', 150, 30, 50, 'Found lots of diamonds here');
        MEMORY_QUICK_COMMANDS.recordDanger(memory, 'Lava lake', [150, 20, 50]);
        const home = MEMORY_QUICK_COMMANDS.getHome(memory);
        console.log('Home position:', home);
        console.log('✓ Long-term memory working\n');
        
        // Test 4: Skills
        console.log('Test 4: Skill learning...');
        MEMORY_QUICK_COMMANDS.learnSkill(memory, 'survive_night', [
            'gather_wood',
            'craft_planks',
            'craft_bed',
            'sleep'
        ], 0.85);
        const skill = MEMORY_QUICK_COMMANDS.getSkill(memory, 'survive_night');
        console.log('Learned skill:', skill);
        MEMORY_QUICK_COMMANDS.updateSkill(memory, 'survive_night', true);
        console.log('✓ Skill system working\n');
        
        // Test 5: Personality
        console.log('Test 5: Personality system...');
        const initialMood = MEMORY_QUICK_COMMANDS.getMood(memory);
        console.log('Initial mood:', initialMood);
        
        MEMORY_QUICK_COMMANDS.recordSuccess(memory, 'Survived 10 hours');
        const successMood = MEMORY_QUICK_COMMANDS.getMood(memory);
        const fear = MEMORY_QUICK_COMMANDS.getFearLevel(memory);
        console.log('After success - mood:', successMood, 'fear:', fear);
        
        MEMORY_QUICK_COMMANDS.recordTrauma(memory, 'Died to creeper');
        const traumaMood = MEMORY_QUICK_COMMANDS.getMood(memory);
        const newFear = MEMORY_QUICK_COMMANDS.getFearLevel(memory);
        console.log('After trauma - mood:', traumaMood, 'fear:', newFear);
        console.log('✓ Personality system working\n');
        
        // Test 6: Failure tracking
        console.log('Test 6: Failure tracking...');
        MEMORY_QUICK_COMMANDS.recordFailure(memory, 'mine_diamonds');
        MEMORY_QUICK_COMMANDS.recordFailure(memory, 'mine_diamonds');
        const shouldAbort = MEMORY_QUICK_COMMANDS.shouldAbortAction(memory, 'mine_diamonds');
        console.log('Should abort after 2 failures:', shouldAbort);
        MEMORY_QUICK_COMMANDS.resetFailure(memory, 'mine_diamonds');
        const shouldAbortAfterReset = MEMORY_QUICK_COMMANDS.shouldAbortAction(memory, 'mine_diamonds');
        console.log('Should abort after reset:', shouldAbortAfterReset);
        console.log('✓ Failure tracking working\n');
        
        // Test 7: Goals
        console.log('Test 7: Goal tracking...');
        MEMORY_QUICK_COMMANDS.addGoal(memory, 'Get diamond pickaxe');
        MEMORY_QUICK_COMMANDS.addGoal(memory, 'Build nether portal');
        let goals = MEMORY_QUICK_COMMANDS.getGoals(memory);
        console.log('Active goals:', goals);
        MEMORY_QUICK_COMMANDS.completeGoal(memory, 'Get diamond pickaxe');
        goals = MEMORY_QUICK_COMMANDS.getGoals(memory);
        console.log('After completing one:', goals);
        console.log('✓ Goal tracking working\n');
        
        // Test 8: Diary
        console.log('Test 8: Diary generation...');
        MEMORY_QUICK_COMMANDS.addDiaryEntry(memory, 'Manual diary entry about today');
        const autoDiary = MEMORY_QUICK_COMMANDS.autoGenerateDiary(memory);
        console.log('Auto-generated diary:', autoDiary);
        console.log('✓ Diary system working\n');
        
        // Test 9: Memory retrieval
        console.log('Test 9: Intelligent memory retrieval...');
        const relevantMemories = MEMORY_QUICK_COMMANDS.getRelevantMemories(
            memory,
            'I need to survive the night'
        );
        console.log('For situation "survive night":');
        console.log('  Short-term:', relevantMemories.short_term.slice(0, 2));
        console.log('  Skills:', relevantMemories.skills.map(s => s.name));
        console.log('✓ Memory retrieval working\n');
        
        // Test 10: Statistics
        console.log('Test 10: Memory statistics...');
        const stats = MEMORY_QUICK_COMMANDS.getStats(memory);
        console.log('Memory stats:', stats);
        console.log('✓ Statistics working\n');
        
        // Test 11: System prompt formatting
        console.log('Test 11: System prompt generation...');
        const systemPrompt = mockAgent.memory_prompter.buildSystemPrompt('exploring cave');
        console.log('System prompt length:', systemPrompt.length, 'characters');
        console.log('Contains agent name:', systemPrompt.includes(mockAgent.name));
        console.log('Contains personality:', systemPrompt.includes('personality'));
        console.log('Contains memory hints:', systemPrompt.includes('Short-term events'));
        console.log('✓ System prompt generation working\n');
        
        // Test 12: Action result handling
        console.log('Test 12: Action result handling...');
        mockAgent.memory_prompter.handleActionResult('mine_iron', 'Successfully mined 3 iron', 25);
        mockAgent.memory_prompter.handleActionResult('craft_bed', 'Crafted bed successfully', 20);
        const moodAfterSuccess = MEMORY_QUICK_COMMANDS.getMood(memory);
        console.log('Mood after successful actions:', moodAfterSuccess);
        console.log('✓ Action result handling working\n');
        
        // Summary
        console.log('========== TEST COMPLETE ==========');
        console.log('✓ All memory systems operational!');
        console.log('\nMemory files created in: bots/TestBot/memories/');
        console.log('  - short_term_memory.json');
        console.log('  - long_term_memory.json');
        console.log('  - skill_memory.json');
        console.log('  - personality_state.json');
        console.log('  - diary.json');
        console.log('  - failure_memory.json');
        console.log('\nNext steps:');
        console.log('1. Integrate into Agent class');
        console.log('2. Update system prompt building');
        console.log('3. Add action result recording');
        console.log('4. Add death handling');
        console.log('5. Start bot and observe memory evolution\n');
        
        return true;
        
    } catch (error) {
        console.error('\n✗ TEST FAILED:', error.message);
        console.error(error.stack);
        return false;
    }
}

// Run test if this is main module
if (import.meta.url === `file://${process.argv[1]}`) {
    testMemorySystem().then(success => {
        process.exit(success ? 0 : 1);
    });
}

export default testMemorySystem;
